-- ==============================================================
-- V8: Catálogo de enfermedades y tratamientos
-- ==============================================================
-- enfermedades: nombre, descripción, especialidad relacionada (texto libre) y
--   estado activo.
-- enfermedad_tratamientos: lista de tratamientos por enfermedad
--   (@ElementCollection). FK con borrado en cascada.
-- En testing se crean solas (ddl-auto=update); en producción (validate)
-- ejecutar este script en Neon ANTES de desplegar.
-- ==============================================================

CREATE TABLE IF NOT EXISTS enfermedades (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                   VARCHAR(255) NOT NULL,
    descripcion              TEXT,
    especialidad_relacionada VARCHAR(255),
    activo                   BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS enfermedad_tratamientos (
    enfermedad_id BIGINT NOT NULL REFERENCES enfermedades(id) ON DELETE CASCADE,
    tratamiento   VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_enf_tratamientos_enfermedad
    ON enfermedad_tratamientos (enfermedad_id);
