package com.ejemplo.vitsync.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.Data;

/**
 * Request body for {@code POST /api/auth/verify}.
 *
 * <p>Validation: the code is exactly 6 digits (as generated by
 * {@code AuthService#register}); the email is RFC-bounded to 254 chars.</p>
 *
 * @author VitSync Team
 * @version 2.0
 * @since 1.0
 */
@Data
public class VerifyRequest {

    @NotBlank(message = "El email es obligatorio")
    @Email(message = "El email debe ser válido")
    @Size(max = 254, message = "El email no puede superar 254 caracteres")
    private String email;

    @NotBlank(message = "El código es obligatorio")
    @Pattern(regexp = "^\\d{6}$", message = "El código debe tener 6 dígitos")
    private String code;
}
